spring:
  datasource:
    url: jdbc:mysql://efub-twitter.c1cc6404cqfg.ap-northeast-2.rds.amazonaws.com:3306/efubtwitter?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: admin
    password: omj030107!!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

